version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    ports:
      - "8088:8088"
    depends_on:
      - namenode
      - datanode

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
      - namenode
      - datanode
      - resourcemanager

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    ports:
      - "5432:5432"

  huedb:
    image: postgres:12.1-alpine
    container_name: huedb
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"

  hue:
    image: gethue/hue:4.6.0
    container_name: hue
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083 huedb:5432"
    ports:
      - "8888:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    depends_on:
      - huedb

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2182:2181"  # Alterado para a porta 2182

  hbase:
    image: harisekhon/hbase:1.3
    container_name: hbase
    ports:
      - "16010:16010"
      - "16000:16000"
      - "16201:16201"
      - "16020:16020"
      - "2181:2181"
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088 zookeeper:2181"
    volumes:
      - ./hbase-data:/hbase_data  # Volume persistente
      - ./hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - zookeeper

  hbase-thrift:
    image: harisekhon/hbase:1.3
    container_name: hbase-thrift
    ports:
      - "9090:9090"
    environment:
      SERVICE_PRECONDITION: "hbase:16000"
    depends_on:
      - hbase

  pig:
    image: moander/pig
    container_name: pig
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088 hbase:16000"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - hbase
    volumes:
      - ./data/processed:/data/processed
      - ./pig-config:/opt/pig/conf
      - ./pig-scripts:/opt/pig/scripts
    command: /bin/bash -c "pig -x mapreduce"
    ports:
      - "18080:18080"
    stdin_open: true
    tty: true

volumes:
  namenode:
  datanode:
  pg_data:
  hbase_data: