version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    networks:
      - hadoop_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
    depends_on:
      - namenode
    networks:
      - hadoop_network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    ports:
      - "8088:8088"
    depends_on:
      - namenode
      - datanode
    networks:
      - hadoop_network

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
      - namenode
      - datanode
      - resourcemanager
    networks:
      - hadoop_network

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    ports:
      - "5432:5432"
    networks:
      - hadoop_network

  huedb:
    image: postgres:12.1-alpine
    container_name: huedb
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"
    networks:
      - hadoop_network

  hue:
    image: gethue/hue:4.6.0
    container_name: hue
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083 huedb:5432"
    ports:
      - "8888:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    depends_on:
      - huedb
    networks:
      - hadoop_network

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2182:2181"  # Alterado para a porta 2182
    networks:
      - hadoop_network

  hbase:
    image: harisekhon/hbase:1.3
    container_name: hbase
    ports:
      - "16010:16010"
      - "16000:16000"
      - "16201:16201"
      - "16020:16020"
      - "2181:2181"
      - "9090:9090" # Thrift API
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088 zookeeper:2181"
    volumes:
      - ./hbase-data:/hbase_data  # Volume persistente
      - ./hbase-site.xml:/opt/hbase/conf/hbase-site.xml
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - zookeeper
    networks:
      - hadoop_network

  pig:
    image: moander/pig
    container_name: pig
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088 hbase:16000"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - hbase
    volumes:
      - ./data/processed:/data/processed
      - ./pig-config:/opt/pig/conf
      - ./pig-scripts:/opt/pig/scripts
    command: /bin/bash -c "pig -x mapreduce"
    ports:
      - "18080:18080"
    stdin_open: true
    tty: true
    networks:
      - hadoop_network

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data
    ports:
      - "6006:6006"  # PHOENIX_PORT
      - "4317:4317"  # PHOENIX_GRPC_PORT
      - "9091:9090"
    depends_on:
      - hbase  # Certifica-te de que o Phoenix depende do HBase
    networks:
      - hadoop_network

volumes:
  namenode:
  datanode:
  pg_data:
  hbase_data:
  phoenix_data:
    driver: local

networks:
  hadoop_network:
    driver: bridge
